config/routes.rb
PhotoCloud::Application.routes.draw do

  get "session/sign_in"

  get "session/sign_out"

  post "session/sign_in"
  post "session/sign_out"

  resources :users

  resources :albums

  get "welcome/index"

  resources :images

   root :to => 'welcome#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :images, :dependent => :destroy
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :name, :photo, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at, :album_id, :user_id
  belongs_to :album
  belongs_to :user
  
    has_attached_file :photo,
      :styles => {
      :thumb  => "100x100",
      :medium => "200x200",
      :large => "600x400"
  },
  :storage => :s3,
  :s3_credentials => { :access_key_id     => ENV['S3_KEY'],
                       :secret_access_key => ENV['S3_SECRET'] },
  :path => ":attachment/:id/:style.:extension",
  :bucket => 'photocloud-jw'
  
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password_digest, :first_name, :last_name
	has_secure_password
	validates :email, :password, :presence => true
	validates :email, :uniqueness => true
	attr_accessible :email, :password, :password_confirmation
	has_many :images
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
before_filter :check_that_user_signed_in
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def check_that_user_signed_in
  	if session[:user_id].nil? then
    	redirect_to session_sign_in_path
  	end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
before_filter :check_that_user_signed_in
  # GET /images
  # GET /images.json
  def index
    @images = Image.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def sign_in
    entered_email = params[:entered_email]
    if not entered_email.nil? then
      user = User.find_by_email(entered_email)
      if user && user.authenticate(params[:entered_password]) then 
        session[:user_id] = user.id
        redirect_to root_path
      else
        redirect_to session_sign_in_path, :alert => 'That email address and password are not recognized.'
      end
    end
    # If we get here, Rails automatically renders the view at
    # app/views/session/sign_in.html.erb.  
  end
  
  def sign_out
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :check_that_user_signed_in, :except => [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save then
      session[:user_id] = @user.id
      respond_to do |format|
        format.html { redirect_to root_url }
        format.json { render :json => @user, :status => :created,
                             :location => @user }
      end
    else
      respond_to do |format|
        format.html { render :action => "new" }
        format.json { render :json => @user.errors,
                             :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def display_email(user_id)
  		user = User.find(user_id)
  		if user then user.email else "Unknown" end
	end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_for @album, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                albums_path, :class => 'btn' %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/albums/index.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1>My <%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<div class="row">
  <ul class="thumbnails pull-left">
    <% @albums.each do |album| %>
      <li class="span2">
        <div class="thumbnail well">

          <% if album.images.empty? %>
            <p><%= image_tag ("http://lorempixel.com/100/100/nature/") %></p>
          <% else %>
              <% album.images.find(1) do |image| %>
                <p><%= image_tag(image.photo(:medium)) %></p>
              <% end %>
          <% end %>

            <p><%= link_to album.name, album_path(album) %></p>
            <p><%= album.description %></p>
            <p>          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_album_path(album), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      album_path(album),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %></p>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<hr />
<p><%= link_to t('.new', :default => t("helpers.links.new")),
            new_album_path,
            :class => 'btn btn-primary btn-large' %></p>

app/views/albums/new.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/albums/show.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1><%=t '.title', :default => @album.name %></h1>
</div>

<ul class="thumbnails">

  <% if @album.images.empty? %>
    <h2>No Images In Current Album</h2>
  <% else %>
    <% @album.images.each do |image| %>
        <li class="span2">
          
            <p><%= link_to image_tag(image.photo(:medium), :height => '120', :class => 'img-polaroid'), image_path(image) %></p>
            <div class="thumbnail well center">
            <p><%= image.name %></p>
            <p>By: <%= image.user.first_name %> <%= image.user.last_name %></p>
          </div>
        </li>
    <% end %>
  <% end %>
</ul>



<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              albums_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_album_path(@album), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              album_path(@album),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/images/_form.html.erb
<%= form_for @image, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :photo, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :photo %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :album_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :album_id, Album.all.collect{|album| [album.name, album.id]} %>
    </div>
  </div>

  <%= f.hidden_field :user_id, :value => session[:user_id] %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                images_path, :class => 'btn' %>
  </div>

<% end %>

app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<div class="well">
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:photo_file_name) %></th>
      <th><%= model_class.human_attribute_name(:photo_content_type) %></th>
      <th><%= model_class.human_attribute_name(:photo_file_size) %></th>
      <th><%= model_class.human_attribute_name(:photo_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:album) %></th>
      <th><%= model_class.human_attribute_name(:user) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image.id, image_path(image) %></td>
        <td><%= image_tag image.photo(:thumb) %></td>
        <td><%= image.name %></td>
        <td><%= image.photo_file_name %></td>
        <td><%= image.photo_content_type %></td>
        <td><%= image.photo_file_size %></td>
        <td><%= image.photo_updated_at %></td>
        <td><%= image.album.name %></td>
        <td><%= image.user.email %></td>
        <td><%= image.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_image_path(image), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      image_path(image),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_image_path,
            :class => 'btn btn-primary' %>

app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/show.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => @image.name %></h1>
  <h2>Photo By: <%= @image.user.email %></h2>
</div>

<dl class="dl-horizontal">
  <dd><%= image_tag(@image.photo.url, :class => "img-rounded") %></dd>
</dl>



<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              images_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_image_path(@image), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              image_path(@image),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoCloud</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>          


<!--START==============NAV BAR============================-->
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="/" class="brand"><img class="logo" src="/assets/logo_small.png"> PhotoCloud</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "New Image", new_image_path %></li>
          <li><%= link_to "Albums", albums_path %></li>
        </ul>
        <ul class="nav pull-right">

          <% if not session[:user_id].nil? then %>
            <li><%= link_to display_email(session[:user_id]) %></li>
            <li><%= link_to 'Sign out', session_sign_out_path %></li>
          <% else %>
            <li><%= link_to 'Sign In', session_sign_in_path %></li> 
            <li><%= link_to 'Sign Up', new_user_path %></li>
          <% end %>

        </ul>
      </div>
    </div>
  </div>
</div>
<!--END==============NAV BAR============================-->


<div class="container">
  <div class="row">
    <div class="span12"><%= yield %></div>
  </div>
</div>

</body>
</html>

app/views/session/sign_in.html.erb
<h1>Sign-in Form</h1>
<%= form_tag :action => 'sign_in' do %>

<p>Your email: <%= text_field_tag :entered_email %></p>

<p>Password: <%= password_field_tag :entered_password %>

<%= submit_tag 'Sign in' %>

<% end %>

<p><%= link_to "Create a new account", new_user_path %></p>

<p id="alert"><%= alert %></p>

app/views/session/sign_out.html.erb
<h1>You are now signed out</h1>

<%= link_to 'Sign in', session_sign_in_path %>


app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :password_digest %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:password_digest) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<h1>Create a new account</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="field form-inline">
    <%= f.text_field :first_name, :placeholder => "First Name"%>
    <%= f.text_field :last_name, :placeholder => "Last Name" %><br />
  </div>
</div><br />
<div class="row">
  <div class="field">
    <%= f.text_field :email, :placeholder => "Email Address" %>
  </div><br />
  <div class="field">
    <%= f.password_field :password, :placeholder => "Password" %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
  </div><br />
  <div class="actions">
    <%= f.submit :class => 'btn-primary btn-large' %>
  </div>
</div>

<% end %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password_digest) %>:</strong></dt>
  <dd><%= @user.password_digest %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/welcome/index.html.erb
<div class="hero-unit">
  <h1>PhotoCloud</h1>
  <p>Simple cloud-based photo and video sharing.</p>
  <p>
    <a class="btn btn-primary btn-large" href="/albums/new">
      Create an Album
    </a>
    <a class="btn btn-primary btn-large" href="/images/new">
      Upload an Image
    </a>
  </p>
</div>